### ISSUE TITLE
'Cannot find module' error

### ISSUE THREAD

**Issue by Berkmann18** [mntnr/name-your-contributors#84]
### What I did?
```bash
yarn add name-your-contributors
node nyc.js
```
_nyc.js_:
```js
const nyc = require('name-your-contributors')

nyc.repoContributors({
    token: process.env.GITHUB_TOKEN,
    user: 'mntnr',
    repo: 'name-your-contributors'
  }).then(res => console.log('NYC results=', res), console.error)
```

### What I got
```bash
Error: Cannot find module 'name-your-contributors'
at Function.Module._resolveFilename (internal/modules/cjs/loader.js:587:15)
at Function.Module._load (internal/modules/cjs/loader.js:513:25)
at Module.require (internal/modules/cjs/loader.js:643:17)
at require (internal/modules/cjs/helpers.js:22:18)
at Object.<anonymous> (/mnt/c/Users/max/Projects/all-contributors-cli/src/discover/nyc.js:1:75)
at Module._compile (internal/modules/cjs/loader.js:707:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:718:10)
at Module.load (internal/modules/cjs/loader.js:605:32)
at tryModuleLoad (internal/modules/cjs/loader.js:544:12)
at Function.Module._load (internal/modules/cjs/loader.js:536:3)
```

I noticed this package has **no** `index.js` at the root which explains why I got this error and unless it wasn't intentional, the examples don't reflect how to actually use that package.

Also, using `name-your-contributors/src` instead gives this error:
```bash
Error: Cannot find module 'name-your-contributors'
at Function.Module._resolveFilename (internal/modules/cjs/loader.js:587:15)
at Function.Module._load (internal/modules/cjs/loader.js:513:25)
at Module.require (internal/modules/cjs/loader.js:643:17)
at require (internal/modules/cjs/helpers.js:22:18)
at Object.<anonymous> (/mnt/c/Users/max/Projects/all-contributors-cli/src/discover/nyc.js:1:75)
at Module._compile (internal/modules/cjs/loader.js:707:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:718:10)
at Module.load (internal/modules/cjs/loader.js:605:32)
at tryModuleLoad (internal/modules/cjs/loader.js:544:12)
at Function.Module._load (internal/modules/cjs/loader.js:536:3)
```

**Comment by RichardLitt** [comment]
The examples, you're right, are broken. I've added a `main` pointer to `src/index.js`. It should work now (although check out #85). I pushed, but I'm using semantic-release, and I forget if it is still working; I may need to republish it manually. Let me know if you're still running into an issue. Thanks for logging this.

**Comment by Berkmann18** [comment]
@RichardLitt The commit in d4abe6cc738fcac05e201d63dc60107e9ac8563c seems to have been ignored by TravisCI (and consequently by Semantic Release) possibly due to 9cd8ab07b9dd2576177156e28b7597c1c42eead4 which made TravisCI skip it (judging by the fact there's no commit status near the former commit).
I don't think you need to republish manually but re-running the build for d4abe6cc738fcac05e201d63dc60107e9ac8563c should get that published.
