### ISSUE TITLE
Before and after need to be specified when requiring

### ISSUE THREAD

**Issue by RichardLitt** [mntnr/name-your-contributors#85]
See below. You shouldn't need to specify `before` and `after`.

```js
const nyc = require('name-your-contributors')

nyc.repoContributors({
	token: process.env.GITHUB_TOKEN,
	user: 'mntnr',
	repo: 'name-your-contributors',
	// Below
	before: new Date(),
	after: new Date(0)
	}).then(//do something with the results
	)
})
```

**Comment by Berkmann18** [comment]
FYI, the build shows this:
```
npm ERR cipm can only install packages when your package.json and package-lock.json or npm-shrinkwrap.json are in sync. Please update your lock file with `npm install` before continuing
```

**Comment by RichardLitt** [comment]
Thanks! Let's get this working for all-contributors! :D

**Comment by Berkmann18** [comment]
@RichardLitt I just got this error on `name-your-contributors@3.4.0` using the same code I provided in #84:

```js
  const b = before.toISOString()
^
TypeError: Cannot read property 'toISOString' of undefined
at repoSubQuery (/mnt/c/Users/max/Projects/all-contributors-cli/node_modules/name-your-contributors/src/queries.js:51:20)
at Object.repository (/mnt/c/Users/max/Projects/all-contributors-cli/node_modules/name-your-contributors/src/queries.js:99:12)
at Object.repoContributors (/mnt/c/Users/max/Projects/all-contributors-cli/node_modules/name-your-contributors/src/index.js:110:20)
at Object.<anonymous (/mnt/c/Users/max/Projects/all-contributors-cli/src/discover/nyc.js:3:5)
at Module._compile (internal/modules/cjs/loader.js:707:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:718:10)
at Module.load (internal/modules/cjs/loader.js:605:32)
at tryModuleLoad (internal/modules/cjs/loader.js:544:12)
at Function.Module._load (internal/modules/cjs/loader.js:536:3)
at Function.Module.runMain (internal/modules/cjs/loader.js:760:12)
```

**Comment by Berkmann18** [comment]
TravisCI PR done (cf. #87).
I'll have a look at the code to see if I can fix the issue I got above.

**Comment by RichardLitt** [comment]
Pretty sure this is closed now.

**Comment by Berkmann18** [comment]
Yup, I might have missed a mention to resolve this issue in my commit/PR.
